name: Deploy Storybook /apps/docs

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      
      - run: npm run build

      - name: Deploy Storybook
      
        working-directory: ./apps/docs
        run: npm run release-storybook -- --ci --existing-output-dir=storybook-static
        env:
          GH_TOKEN: ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}